name: Build and deploy the application to Koyeb

on:
  schedule:
    - cron: '42 7 * * *'
  push:
    branches:
      - '*'

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          api-token: "${{ secrets.KOYEB_EXAMPLES_APPS_TOKEN }}"
          service-ports: "8000:http"
          service-routes: "/:8000"
          git-run-command: bin/example-go-gin